name: Test
on:
  workflow_dispatch:

jobs:
  test-error-message:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "::error::Filename MY_FILE.TXT doesn't match possible files"
        echo "::group::My title"
        echo "Inside the group ðŸ€"
        echo "::endgroup::"
        echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY